import * as fs from 'fs';
import * as path from 'path';
import { BaseActionTool } from './base-action-tool';
import { ActionToolResult, successResult, errorResult } from '../types';
import { resolveAsset } from '../utils/asset-path';

const DEFAULT_MATERIAL_JSON = JSON.stringify({
    "__type__": "cc.Material",
    "_name": "",
    "_objFlags": 0,
    "__editorExtras__": {},
    "_native": "",
    "_effectAsset": null,
    "_techIdx": 0,
    "_defines": [{}],
    "_states": [{}],
    "_props": [{}]
}, null, 2);

export class ManageMaterial extends BaseActionTool {
    readonly name = 'manage_material';
    readonly description = 'Manage material assets. Actions: create, get_info, set_property, list. Materials control visual appearance of meshes. Use get_info to inspect current properties before modifying. set_property writes the serialized `_props` entry of a standalone .mtl asset and verifies it on disk; materials embedded in an imported model (FBX/glTF subassets) are read-only here.';
    readonly actions = ['create', 'get_info', 'set_property', 'list'];
    readonly inputSchema = {
        type: 'object',
        properties: {
            action: {
                type: 'string',
                enum: ['create', 'get_info', 'set_property', 'list'],
                description: 'Action to perform: create=create new .mtl asset, get_info=query asset info and meta, set_property=write a serialized material property into the .mtl asset, list=list all material assets'
            },
            url: {
                type: 'string',
                description: '[create, get_info, set_property] Asset DB URL or UUID (e.g., db://assets/materials/MyMaterial.mtl). set_property requires a standalone .mtl asset — materials embedded in an imported model (FBX/glTF subassets) are not writable through this tool.'
            },
            property: {
                type: 'string',
                description: '[set_property] Serialized material property name, as it appears in the .mtl `_props` block (e.g., mainTexture, albedo, occlusionMap)'
            },
            value: {
                description: '[set_property] Value written verbatim into `_props`. Use the serialized form: numbers/booleans as-is, colors as {"__type__":"cc.Color","r":255,"g":0,"b":0,"a":255}, asset references as {"__uuid__":"<uuid>","__expectedType__":"cc.Texture2D"}. Pass null to clear the property (the key is removed so the effect default applies).'
            },
            pattern: {
                type: 'string',
                description: '[list] Glob pattern to filter materials (default: db://assets/**/*.mtl)',
                default: 'db://assets/**/*.mtl'
            }
        },
        required: ['action']
    };

    protected actionHandlers: Record<string, (args: Record<string, any>) => Promise<ActionToolResult>> = {
        create: (args) => this.createMaterial(args),
        get_info: (args) => this.getMaterialInfo(args),
        set_property: (args) => this.setMaterialProperty(args),
        list: (args) => this.listMaterials(args),
    };

    private async createMaterial(args: any): Promise<ActionToolResult> {
        try {
            if (!args.url) return errorResult('url is required for create');
            const result = await Editor.Message.request('asset-db', 'create-asset', args.url, DEFAULT_MATERIAL_JSON);
            return successResult(
                { url: args.url, uuid: (result as any)?.uuid },
                `Material created at ${args.url}`
            );
        } catch (err: any) {
            return errorResult(err.message);
        }
    }

    private async getMaterialInfo(args: any): Promise<ActionToolResult> {
        try {
            if (!args.url) return errorResult('url is required for get_info');
            const info = await Editor.Message.request('asset-db', 'query-asset-info', args.url);
            let meta: any = null;
            try {
                meta = await Editor.Message.request('asset-db', 'query-asset-meta', args.url);
            } catch {
                // meta may not be available for all assets
            }
            return successResult({ info, meta });
        } catch (err: any) {
            return errorResult(err.message);
        }
    }

    /**
     * Write a property into the material's serialized `_props` block.
     *
     * The previous implementation wrote `meta.userData[property]` and reported success.
     * `userData` is importer configuration — it is not the material's property table, so
     * the serialized value never changed, survived reimport, and the runtime kept
     * resolving the old reference. A meta-only write cannot affect a material, so it must
     * never be reported as one (#24).
     *
     * Only standalone `.mtl` assets are writable here. A material embedded in an imported
     * model (FBX/glTF subasset) is regenerated by that model's importer and has no
     * `.mtl` file of its own; that case returns an explicit unsupported error rather than
     * a success the caller cannot verify.
     */
    private async setMaterialProperty(args: any): Promise<ActionToolResult> {
        if (!args.url) return errorResult('url is required for set_property');
        if (!args.property) return errorResult('property is required for set_property');
        if (args.value === undefined) return errorResult('value is required for set_property (pass null to clear the property)');

        const resolved = await resolveAsset(args.url);
        if (resolved.error) return errorResult(resolved.error);
        if (!resolved.filePath) {
            return errorResult(`Could not resolve an on-disk file for ${args.url}. set_property needs a standalone .mtl asset.`);
        }
        if (path.extname(resolved.filePath).toLowerCase() !== '.mtl') {
            return errorResult(
                `set_property cannot edit '${args.url}': it resolves to ${path.basename(resolved.filePath)}, not a standalone .mtl asset. ` +
                'Materials embedded in an imported model are regenerated by that model\'s importer — ' +
                'edit them in the Inspector, or extract the material to a .mtl asset first.'
            );
        }

        let material: any;
        try {
            material = JSON.parse(fs.readFileSync(resolved.filePath, 'utf-8'));
        } catch (err: any) {
            return errorResult(`Failed to read material asset ${resolved.filePath}: ${err.message}`);
        }
        if (!material || material.__type__ !== 'cc.Material') {
            return errorResult(`${args.url} is not a cc.Material asset (found __type__=${material?.__type__ ?? 'none'})`);
        }

        const techIdx: number = typeof material._techIdx === 'number' ? material._techIdx : 0;
        if (!Array.isArray(material._props)) material._props = [];
        while (material._props.length <= techIdx) material._props.push({});
        const props = material._props[techIdx] || (material._props[techIdx] = {});

        const clearing = args.value === null;
        if (clearing) delete props[args.property];
        else props[args.property] = args.value;

        try {
            await Editor.Message.request('asset-db', 'save-asset', args.url, JSON.stringify(material, null, 2));
        } catch (err: any) {
            return errorResult(`save-asset rejected ${args.url}: ${err.message}`);
        }
        try {
            await Editor.Message.request('asset-db', 'reimport-asset', args.url);
        } catch (err: any) {
            return errorResult(`Material written but reimport-asset failed for ${args.url}: ${err.message}`);
        }

        // Read the asset back. A success envelope here means the serialized property
        // actually changed on disk — never that a message resolved without throwing.
        const verification = this.verifySavedProperty(resolved.filePath, techIdx, args.property, args.value, clearing);
        if (!verification.verified) return errorResult(verification.error!);

        return successResult(
            { url: args.url, file: resolved.filePath, property: args.property, value: args.value, techniqueIndex: techIdx, cleared: clearing },
            clearing
                ? `Property '${args.property}' cleared from material ${args.url} (verified on disk)`
                : `Property '${args.property}' set on material ${args.url} (verified on disk)`
        );
    }

    private verifySavedProperty(
        filePath: string, techIdx: number, property: string, value: any, clearing: boolean
    ): { verified: boolean; error?: string } {
        let saved: any;
        try {
            saved = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
        } catch (err: any) {
            return { verified: false, error: `Could not re-read ${filePath} to verify the write: ${err.message}` };
        }
        const savedProps = Array.isArray(saved?._props) ? saved._props[techIdx] : undefined;
        if (clearing) {
            if (savedProps && Object.prototype.hasOwnProperty.call(savedProps, property)) {
                return { verified: false, error: `Wrote the material but '${property}' is still present in _props[${techIdx}] after reimport.` };
            }
            return { verified: true };
        }
        if (!savedProps || JSON.stringify(savedProps[property]) !== JSON.stringify(value)) {
            return { verified: false, error: `Wrote the material but '${property}' did not persist in _props[${techIdx}] after reimport.` };
        }
        return { verified: true };
    }

    private async listMaterials(args: any): Promise<ActionToolResult> {
        try {
            const pattern = args.pattern || 'db://assets/**/*.mtl';
            const assets = await Editor.Message.request('asset-db', 'query-assets', { pattern });
            return successResult({ materials: assets, count: (assets as any[]).length });
        } catch (err: any) {
            return errorResult(err.message);
        }
    }
}
